Repository apache/incubator-kie-kogito-runtimes, pull requests merged in 2023-03, with the labels that each got.

#2829 KOGITO-8727 - Allow to override image in the Data Index Dev Service test
  quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-integration-test-hot-reload/pom.xml
  quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-integration-test-hot-reload/src/test/java/io/quarkus/it/kogito/process/KogitoDevServiceTest.java
Labels: backport-1.35.x

#2836 KOGITO-8761 Reverted call to a new method that doesn't exist in Quarkus LTS
  quarkus/addons/knative/serving/runtime/src/test/java/org/kie/kogito/addons/quarkus/knative/serving/customfunctions/KnativeServiceDiscoveryTestUtil.java
  quarkus/addons/kubernetes/runtime/src/test/java/org/kie/kogito/addons/quarkus/k8s/KnativeServiceDiscoveryTest.java
Labels: backport-1.35.x

#2837 [1.13.x] Bump Quarkus version to 2.13.7.Final
  kogito-build/kogito-dependencies-bom/pom.xml
Labels: backport-1.13.x-blue

#2839 KOGITO-8774 - Data Index Dev Service cannot start due to "Unknown con…
  quarkus/extensions/kogito-quarkus-workflow-extension-common/kogito-quarkus-workflow-common-deployment/src/main/java/org/kie/kogito/quarkus/workflow/deployment/devservices/DataIndexInMemoryContainer.java
Labels: backport-1.35.x

#2851 KOGITO-8800 - Allow to use a separate image for Data Index Dev Servic…
  quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-integration-test-hot-reload/pom.xml
  quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-integration-test-hot-reload/src/test/java/io/quarkus/it/kogito/process/KogitoDevServiceTest.java
Labels: backport-1.35.x

#2898 Release: Fix setup data-index image tag
  .ci/jenkins/Jenkinsfile.deploy
Labels: backport-1.36.x

#2905 Promote Release: Fix setup data-index image tag
  .ci/jenkins/Jenkinsfile.promote
Labels: backport-1.36.x
