Repository apache/incubator-kie-kogito-runtimes, pull requests merged in 2023-02, with the labels that each got.

#2793 KOGITO-8606 - Remove JavaDoc plugin from Kogito as it is not used
  kogito-bom/pom.xml
  kogito-build/kogito-build-no-bom-parent/pom.xml
Labels: backport-1.34.x

#2754 KOGITO-8515 quarkus-openapi-generator updated to 1.2.1
  kogito-build/kogito-dependencies-bom/pom.xml
Labels: backport-1.33.x

#2807 KOGITO-8667 Reorganize GHA
  .github/workflows/kogito-runtimes-pr.yml
  .github/workflows/nightly-quarkus-ecosystem.yaml
  .github/workflows/pr-downstream.yml
  .github/workflows/pr-jenkins.yml
  .github/workflows/pr-kogito-runtimes.yml
  .github/workflows/pr-surefire-report.yml
Labels: skip-ci

#2711 KOGITO-7373 Added custom function for Knative
  kogito-bom/pom.xml
  quarkus/addons/knative/pom.xml
  quarkus/addons/knative/serving/deployment/pom.xml
  quarkus/addons/knative/serving/deployment/src/main/java/org/kie/kogito/addons/quarkus/knative/serving/deployment/customfunctions/KnativeTypeHandler.java
  quarkus/addons/knative/serving/deployment/src/main/resources/META-INF/services/org.kie.kogito.serverless.workflow.parser.FunctionTypeHandler
  quarkus/addons/knative/serving/pom.xml
  quarkus/addons/knative/serving/runtime/pom.xml
  quarkus/addons/knative/serving/runtime/src/main/java/org/kie/kogito/addons/quarkus/knative/serving/customfunctions/KnativeServerlessWorkflowCustomFunction.java
  quarkus/addons/knative/serving/runtime/src/main/java/org/kie/kogito/addons/quarkus/knative/serving/customfunctions/KnativeServiceAddress.java
  quarkus/addons/knative/serving/runtime/src/main/java/org/kie/kogito/addons/quarkus/knative/serving/customfunctions/KnativeServiceDiscovery.java
  quarkus/addons/knative/serving/runtime/src/main/java/org/kie/kogito/addons/quarkus/knative/serving/customfunctions/KnativeServiceIdentifier.java
  quarkus/addons/knative/serving/runtime/src/main/java/org/kie/kogito/addons/quarkus/knative/serving/customfunctions/KnativeServiceRegistry.java
  quarkus/addons/knative/serving/runtime/src/main/java/org/kie/kogito/addons/quarkus/knative/serving/customfunctions/KnativeWorkItemHandler.java
  quarkus/addons/knative/serving/runtime/src/main/java/org/kie/kogito/addons/quarkus/knative/serving/customfunctions/KnativeWorkItemHandlerConfig.java
  quarkus/addons/knative/serving/runtime/src/main/resources/META-INF/beans.xml
  quarkus/addons/knative/serving/runtime/src/main/resources/META-INF/kogito.addon
  quarkus/addons/knative/serving/runtime/src/test/java/org/kie/kogito/addons/quarkus/knative/serving/customfunctions/KnativeServerlessWorkflowCustomFunctionTest.java
  quarkus/addons/knative/serving/runtime/src/test/java/org/kie/kogito/addons/quarkus/knative/serving/customfunctions/KnativeServiceDiscoveryTest.java
  quarkus/addons/knative/serving/runtime/src/test/java/org/kie/kogito/addons/quarkus/knative/serving/customfunctions/KnativeServiceDiscoveryTestUtil.java
  quarkus/addons/knative/serving/runtime/src/test/java/org/kie/kogito/addons/quarkus/knative/serving/customfunctions/KnativeServiceIdentifierTest.java
  quarkus/addons/knative/serving/runtime/src/test/resources/application.properties
  quarkus/addons/knative/serving/runtime/src/test/resources/knative/quarkus-greeting-https.yaml
  quarkus/addons/knative/serving/runtime/src/test/resources/knative/quarkus-greeting.yaml
  quarkus/addons/kubernetes/deployment/pom.xml
  quarkus/addons/kubernetes/runtime/pom.xml
  quarkus/addons/kubernetes/runtime/src/main/java/org/kie/kogito/addons/quarkus/k8s/KnativeResourceDiscovery.java
  quarkus/addons/kubernetes/runtime/src/main/java/org/kie/kogito/addons/quarkus/k8s/KubeResourceDiscovery.java
  quarkus/addons/kubernetes/runtime/src/main/java/org/kie/kogito/addons/quarkus/k8s/parser/KubeURI.java
  quarkus/addons/kubernetes/runtime/src/main/resources/META-INF/beans.xml
  quarkus/addons/kubernetes/runtime/src/test/java/org/kie/kogito/addons/quarkus/k8s/KnativeServiceDiscoveryTest.java
  quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow/pom.xml
Labels: backport-1.35.x
